# Generated by Django 5.1 on 2024-11-03 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
    ]
