# Generated by Django 5.1 on 2024-08-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
    ]
