# Generated by Django 5.1 on 2024-08-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_noticia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
